[TASK] support TYPO3 12
sitegeist/fluid-styleguide pull request #108
Opened 2023-05-10 08:30 UTC by lukasniestroj

* remove support for TYPO3 version 10.4

github action are copied from sitegeist/fluid-components

2023-05-10 08:31 UTC, lukasniestroj commented on Classes/Middleware/StyleguideRouter.php
> -                $GLOBALS['TSFE']->lang = $styleguideLanguage['identifier'];
this needs to be reviewed: I am not sure if this is still a leftover of TYPO3 10.4

2023-09-26 09:19 UTC, ulrichmathes submitted a review, later dismissed
we want to remove compatibility to sitegeist/fluid-components dev-master as its not necessary for TYPO3 v12

2023-09-26 10:08 UTC, ulrichmathes requested changes
Styleguide broken in TYPO3 v11

2023-09-26 10:08 UTC, ulrichmathes commented on Classes/Middleware/StyleguideRouter.php
> +        $extbaseAttribute = new ExtbaseRequestParameters();
The view is not properly initiated in TYPO3 v11.

`Tried resolving a template file for controller action "Standard->index" in format ".html", but none of the paths contained the expected template file (Standard/Index.html). The following paths were checked: /var/www/html/public/typo3conf/ext/fluid_styleguide/Resources/Private/Templates/`

2023-10-11 10:36 UTC, ulrichmathes approved these changes

2024-01-11 12:57 UTC, Kayu84 approved these changes
works under my tested conditions (11.5 / 12.4)

2024-02-15 09:05 UTC, svenpet90 commented
Any update on when this will be merged/released? :)

2024-02-16 10:12 UTC, merged